"""Pydantic schemas for graph analytics and pattern detection."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AnalyticsStatus(str, Enum):
    """Execution status of an analytics run."""
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    GRAPH_UNAVAILABLE = "GRAPH_UNAVAILABLE"
    NO_GRAPH_DATA = "NO_GRAPH_DATA"
    FAILED = "FAILED"


class AnalyticsEngine(str, Enum):
    """Engine used for feature computation."""
    NETWORKX_FALLBACK = "networkx_fallback"
    NEO4J_GDS = "neo4j_gds"
    NONE = "none"


class AlertSeverity(str, Enum):
    """Severity levels for pattern alerts."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    """Workflow status for alerts."""
    OPEN = "OPEN"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CORRECTED = "CORRECTED"
    NEEDS_MORE_INFORMATION = "NEEDS_MORE_INFORMATION"


class EntityGraphFeatures(BaseModel):
    """Computed graph features for a single entity."""
    
    entity_id: str = Field(..., description="Stable node identifier")
    case_id: str = Field(..., description="Originating case ID")
    entity_type: str = Field(..., description="Type of the entity (e.g., PERSON, PHONE)")
    
    # Degree metrics
    degree: int = Field(default=0, ge=0)
    in_degree: int | None = Field(default=None, ge=0)
    out_degree: int | None = Field(default=None, ge=0)
    
    # Specific connectivity counts
    case_count: int = Field(default=0, ge=0)
    unique_neighbour_count: int = Field(default=0, ge=0)
    shared_location_count: int = Field(default=0, ge=0)
    shared_phone_count: int = Field(default=0, ge=0)
    shared_vehicle_count: int = Field(default=0, ge=0)
    
    # Transactions
    transaction_count: int = Field(default=0, ge=0)
    transaction_total: float = Field(default=0.0, ge=0.0)
    transaction_chain_count: int = Field(default=0, ge=0)
    
    # Graph structural properties
    community_id: str | int | None = Field(default=None)
    community_size: int = Field(default=0, ge=0)
    pagerank_score: float = Field(default=0.0, ge=0.0, le=1.0)
    betweenness_score: float = Field(default=0.0, ge=0.0, le=1.0)
    bridge_score: float = Field(default=0.0, ge=0.0, le=1.0)
    
    # Future placeholder
    historical_similarity_score: float | None = Field(default=None, ge=0.0, le=1.0)
    
    # Metadata
    computed_at: datetime
    algorithm_version: str
    analytics_engine: str
    warnings: list[str] = Field(default_factory=list)


class CaseGraphAnalytics(BaseModel):
    """Aggregate graph analytics for a case."""
    
    case_id: str
    node_count: int = Field(default=0, ge=0)
    edge_count: int = Field(default=0, ge=0)
    community_count: int = Field(default=0, ge=0)
    density: float = Field(default=0.0, ge=0.0, le=1.0)
    
    computed_at: datetime
    algorithm_version: str
    analytics_engine: str
    status: AnalyticsStatus
    truncated: bool = Field(default=False)
    warnings: list[str] = Field(default_factory=list)


class PatternAlert(BaseModel):
    """Explainable investigative lead generated by pattern detection."""
    
    alert_id: str
    case_id: str
    pattern_type: str
    severity: AlertSeverity
    score: float = Field(default=0.0, ge=0.0, le=1.0)
    title: str
    explanation: str
    entities_involved: list[str]
    evidence_ids: list[str]
    feature_values: dict[str, Any]
    
    rule_version: str
    model_version: str | None = None
    analytics_engine: str
    algorithm_version: str
    analysis_run_id: str
    
    status: AlertStatus = Field(default=AlertStatus.OPEN)
    requires_human_verification: bool = Field(default=True)
    created_at: datetime


class AnalyticsRunResponse(BaseModel):
    """Response returned when triggering an analytics run."""
    
    analysis_run_id: str
    case_id: str
    status: AnalyticsStatus
    analytics_engine: AnalyticsEngine
    gds_available: bool
    
    node_count: int = Field(default=0, ge=0)
    edge_count: int = Field(default=0, ge=0)
    feature_count: int = Field(default=0, ge=0)
    alert_count: int = Field(default=0, ge=0)
    
    warnings: list[str] = Field(default_factory=list)
    started_at: datetime
    completed_at: datetime
