"""Add analytics features and augment alerts

Revision ID: 0c9585b01b73
Revises: 56def4f0626f
Create Date: 2026-09-02 21:59:51.151692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9585b01b73'
down_revision: Union[str, Sequence[str], None] = '56def4f0626f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_graph_analytics',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('community_count', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('analytics_engine', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cga_analysis_run_id', 'case_graph_analytics', ['analysis_run_id'], unique=False)
    op.create_index('ix_cga_case_id', 'case_graph_analytics', ['case_id'], unique=False)
    op.create_index('ix_cga_created_at', 'case_graph_analytics', ['created_at'], unique=False)
    op.create_table('entity_graph_features',
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('in_degree', sa.Integer(), nullable=True),
    sa.Column('out_degree', sa.Integer(), nullable=True),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('unique_neighbour_count', sa.Integer(), nullable=False),
    sa.Column('shared_location_count', sa.Integer(), nullable=False),
    sa.Column('shared_phone_count', sa.Integer(), nullable=False),
    sa.Column('shared_vehicle_count', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('transaction_total', sa.Float(), nullable=False),
    sa.Column('transaction_chain_count', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=100), nullable=True),
    sa.Column('community_size', sa.Integer(), nullable=False),
    sa.Column('pagerank_score', sa.Float(), nullable=False),
    sa.Column('betweenness_score', sa.Float(), nullable=False),
    sa.Column('bridge_score', sa.Float(), nullable=False),
    sa.Column('historical_similarity_score', sa.Float(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('analytics_engine', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_egf_analysis_run_id', 'entity_graph_features', ['analysis_run_id'], unique=False)
    op.create_index('ix_egf_case_id', 'entity_graph_features', ['case_id'], unique=False)
    op.create_index('ix_egf_created_at', 'entity_graph_features', ['created_at'], unique=False)
    op.create_index('ix_egf_entity_id', 'entity_graph_features', ['entity_id'], unique=False)
    op.add_column('alerts', sa.Column('evidence_ids', sa.JSON(), nullable=True))
    op.add_column('alerts', sa.Column('feature_values', sa.JSON(), nullable=True))
    op.add_column('alerts', sa.Column('rule_version', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('analytics_engine', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('algorithm_version', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('analysis_run_id', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('requires_human_verification', sa.Boolean(), nullable=False))
    op.add_column('alerts', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_index('ix_alerts_analysis_run_id', 'alerts', ['analysis_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_analysis_run_id', table_name='alerts')
    op.drop_column('alerts', 'reviewed_at')
    op.drop_column('alerts', 'requires_human_verification')
    op.drop_column('alerts', 'analysis_run_id')
    op.drop_column('alerts', 'algorithm_version')
    op.drop_column('alerts', 'analytics_engine')
    op.drop_column('alerts', 'model_version')
    op.drop_column('alerts', 'rule_version')
    op.drop_column('alerts', 'feature_values')
    op.drop_column('alerts', 'evidence_ids')
    op.drop_index('ix_egf_entity_id', table_name='entity_graph_features')
    op.drop_index('ix_egf_created_at', table_name='entity_graph_features')
    op.drop_index('ix_egf_case_id', table_name='entity_graph_features')
    op.drop_index('ix_egf_analysis_run_id', table_name='entity_graph_features')
    op.drop_table('entity_graph_features')
    op.drop_index('ix_cga_created_at', table_name='case_graph_analytics')
    op.drop_index('ix_cga_case_id', table_name='case_graph_analytics')
    op.drop_index('ix_cga_analysis_run_id', table_name='case_graph_analytics')
    op.drop_table('case_graph_analytics')
    # ### end Alembic commands ###
