"""initial_schema_users_cases_documents_entities_relationships_jobs_alerts_feedback_audit

Revision ID: 135f524fbc36
Revises: 
Create Date: 2026-09-02 20:53:25.919871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135f524fbc36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.Text(), nullable=True),
    sa.Column('new_state', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target_id', 'audit_logs', ['target_id'], unique=False)
    op.create_index('ix_audit_logs_target_type', 'audit_logs', ['target_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ix_cases_case_number', 'cases', ['case_number'], unique=False)
    op.create_index('ix_cases_created_at', 'cases', ['created_at'], unique=False)
    op.create_index('ix_cases_created_by', 'cases', ['created_by'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_table('investigator_feedback',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('correction_data', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigator_feedback_action', 'investigator_feedback', ['action'], unique=False)
    op.create_index('ix_investigator_feedback_target_id', 'investigator_feedback', ['target_id'], unique=False)
    op.create_index('ix_investigator_feedback_user_id', 'investigator_feedback', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('ix_alerts_case_id', 'alerts', ['case_id'], unique=False)
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_case_id', 'documents', ['case_id'], unique=False)
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('ix_documents_file_type', 'documents', ['file_type'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_entities_case_id', 'extracted_entities', ['case_id'], unique=False)
    op.create_index('ix_extracted_entities_entity_type', 'extracted_entities', ['entity_type'], unique=False)
    op.create_index('ix_extracted_entities_verification_status', 'extracted_entities', ['verification_status'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_jobs_case_id', 'processing_jobs', ['case_id'], unique=False)
    op.create_index('ix_processing_jobs_created_at', 'processing_jobs', ['created_at'], unique=False)
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_table('extracted_relationships',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('source_text_snippet', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['extracted_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['extracted_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_relationships_case_id', 'extracted_relationships', ['case_id'], unique=False)
    op.create_index('ix_extracted_relationships_relation_type', 'extracted_relationships', ['relation_type'], unique=False)
    op.create_index('ix_extracted_relationships_source_entity_id', 'extracted_relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_extracted_relationships_target_entity_id', 'extracted_relationships', ['target_entity_id'], unique=False)
    op.create_index('ix_extracted_relationships_verification_status', 'extracted_relationships', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extracted_relationships_verification_status', table_name='extracted_relationships')
    op.drop_index('ix_extracted_relationships_target_entity_id', table_name='extracted_relationships')
    op.drop_index('ix_extracted_relationships_source_entity_id', table_name='extracted_relationships')
    op.drop_index('ix_extracted_relationships_relation_type', table_name='extracted_relationships')
    op.drop_index('ix_extracted_relationships_case_id', table_name='extracted_relationships')
    op.drop_table('extracted_relationships')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_created_at', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_case_id', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_extracted_entities_verification_status', table_name='extracted_entities')
    op.drop_index('ix_extracted_entities_entity_type', table_name='extracted_entities')
    op.drop_index('ix_extracted_entities_case_id', table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_file_type', table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_index('ix_documents_case_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('ix_alerts_case_id', table_name='alerts')
    op.drop_index('ix_alerts_alert_type', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_investigator_feedback_user_id', table_name='investigator_feedback')
    op.drop_index('ix_investigator_feedback_target_id', table_name='investigator_feedback')
    op.drop_index('ix_investigator_feedback_action', table_name='investigator_feedback')
    op.drop_table('investigator_feedback')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_created_by', table_name='cases')
    op.drop_index('ix_cases_created_at', table_name='cases')
    op.drop_index('ix_cases_case_number', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
