"""Add ML and Similarity models

Revision ID: 26712e160037
Revises: 0c9585b01b73
Create Date: 2026-09-02 22:41:21.919888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26712e160037'
down_revision: Union[str, Sequence[str], None] = '0c9585b01b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_feature_vectors',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('feature_values', sa.JSON(), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cfv_analysis_run_id', 'case_feature_vectors', ['analysis_run_id'], unique=False)
    op.create_index('ix_cfv_case_id', 'case_feature_vectors', ['case_id'], unique=False)
    op.create_index('ix_cfv_created_at', 'case_feature_vectors', ['created_at'], unique=False)
    op.create_index('ix_cfv_feature_version', 'case_feature_vectors', ['feature_version'], unique=False)
    op.create_table('model_predictions',
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('top_features', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requires_human_verification', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mp_case_id', 'model_predictions', ['case_id'], unique=False)
    op.create_index('ix_mp_created_at', 'model_predictions', ['created_at'], unique=False)
    op.create_index('ix_mp_entity_id', 'model_predictions', ['entity_id'], unique=False)
    op.create_index('ix_mp_model_version', 'model_predictions', ['model_version'], unique=False)
    op.create_index('ix_mp_prediction_type', 'model_predictions', ['prediction_type'], unique=False)
    op.create_table('similarity_results',
    sa.Column('current_case_id', sa.String(length=36), nullable=False),
    sa.Column('similar_case_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('matched_features', sa.JSON(), nullable=True),
    sa.Column('differing_features', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sr_analysis_run_id', 'similarity_results', ['analysis_run_id'], unique=False)
    op.create_index('ix_sr_created_at', 'similarity_results', ['created_at'], unique=False)
    op.create_index('ix_sr_current_case_id', 'similarity_results', ['current_case_id'], unique=False)
    op.create_index('ix_sr_similar_case_id', 'similarity_results', ['similar_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sr_similar_case_id', table_name='similarity_results')
    op.drop_index('ix_sr_current_case_id', table_name='similarity_results')
    op.drop_index('ix_sr_created_at', table_name='similarity_results')
    op.drop_index('ix_sr_analysis_run_id', table_name='similarity_results')
    op.drop_table('similarity_results')
    op.drop_index('ix_mp_prediction_type', table_name='model_predictions')
    op.drop_index('ix_mp_model_version', table_name='model_predictions')
    op.drop_index('ix_mp_entity_id', table_name='model_predictions')
    op.drop_index('ix_mp_created_at', table_name='model_predictions')
    op.drop_index('ix_mp_case_id', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('ix_cfv_feature_version', table_name='case_feature_vectors')
    op.drop_index('ix_cfv_created_at', table_name='case_feature_vectors')
    op.drop_index('ix_cfv_case_id', table_name='case_feature_vectors')
    op.drop_index('ix_cfv_analysis_run_id', table_name='case_feature_vectors')
    op.drop_table('case_feature_vectors')
    # ### end Alembic commands ###
