"""Add ingestion tracking fields

Revision ID: 56def4f0626f
Revises: 135f524fbc36
Create Date: 2026-09-02 21:14:01.389168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56def4f0626f'
down_revision: Union[str, Sequence[str], None] = '135f524fbc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_entities', sa.Column('source_record_type', sa.String(length=50), nullable=True))
    op.add_column('extracted_entities', sa.Column('source_record_id', sa.String(length=100), nullable=True))
    op.add_column('extracted_entities', sa.Column('graph_sync_status', sa.String(length=50), nullable=False))
    op.add_column('extracted_entities', sa.Column('graph_sync_error', sa.Text(), nullable=True))
    op.add_column('extracted_entities', sa.Column('graph_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_extracted_entities_graph_sync', 'extracted_entities', ['graph_sync_status'], unique=False)
    op.create_index('ix_extracted_entities_source', 'extracted_entities', ['source_record_type', 'source_record_id'], unique=False)
    op.add_column('extracted_relationships', sa.Column('source_record_type', sa.String(length=50), nullable=True))
    op.add_column('extracted_relationships', sa.Column('source_record_id', sa.String(length=100), nullable=True))
    op.add_column('extracted_relationships', sa.Column('graph_sync_status', sa.String(length=50), nullable=False))
    op.add_column('extracted_relationships', sa.Column('graph_sync_error', sa.Text(), nullable=True))
    op.add_column('extracted_relationships', sa.Column('graph_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_extracted_rel_graph_sync', 'extracted_relationships', ['graph_sync_status'], unique=False)
    op.create_index('ix_extracted_rel_source', 'extracted_relationships', ['source_record_type', 'source_record_id'], unique=False)
    op.add_column('processing_jobs', sa.Column('total_rows', sa.Integer(), nullable=False))
    op.add_column('processing_jobs', sa.Column('processed_rows', sa.Integer(), nullable=False))
    op.add_column('processing_jobs', sa.Column('rejected_rows', sa.Integer(), nullable=False))
    op.add_column('processing_jobs', sa.Column('error_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'error_summary')
    op.drop_column('processing_jobs', 'rejected_rows')
    op.drop_column('processing_jobs', 'processed_rows')
    op.drop_column('processing_jobs', 'total_rows')
    op.drop_index('ix_extracted_rel_source', table_name='extracted_relationships')
    op.drop_index('ix_extracted_rel_graph_sync', table_name='extracted_relationships')
    op.drop_column('extracted_relationships', 'graph_synced_at')
    op.drop_column('extracted_relationships', 'graph_sync_error')
    op.drop_column('extracted_relationships', 'graph_sync_status')
    op.drop_column('extracted_relationships', 'source_record_id')
    op.drop_column('extracted_relationships', 'source_record_type')
    op.drop_index('ix_extracted_entities_source', table_name='extracted_entities')
    op.drop_index('ix_extracted_entities_graph_sync', table_name='extracted_entities')
    op.drop_column('extracted_entities', 'graph_synced_at')
    op.drop_column('extracted_entities', 'graph_sync_error')
    op.drop_column('extracted_entities', 'graph_sync_status')
    op.drop_column('extracted_entities', 'source_record_id')
    op.drop_column('extracted_entities', 'source_record_type')
    # ### end Alembic commands ###
