"""Add extraction fields for Milestone 8

Revision ID: 5fc125e5f8d3
Revises: b0d56ca02c54
Create Date: 2026-09-03 00:22:18.850306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc125e5f8d3'
down_revision: Union[str, Sequence[str], None] = 'b0d56ca02c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_entities', sa.Column('original_value', sa.String(length=255), nullable=True))
    op.add_column('extracted_entities', sa.Column('source_text', sa.Text(), nullable=True))
    op.add_column('extracted_entities', sa.Column('start_offset', sa.Integer(), nullable=True))
    op.add_column('extracted_entities', sa.Column('end_offset', sa.Integer(), nullable=True))
    op.add_column('extracted_entities', sa.Column('extraction_provider', sa.String(length=100), nullable=True))
    op.add_column('extracted_entities', sa.Column('extraction_version', sa.String(length=50), nullable=True))
    op.add_column('extracted_entities', sa.Column('reviewer_identity', sa.String(length=100), nullable=True))
    op.add_column('extracted_entities', sa.Column('review_rationale', sa.Text(), nullable=True))
    op.add_column('extracted_relationships', sa.Column('start_offset', sa.Integer(), nullable=True))
    op.add_column('extracted_relationships', sa.Column('end_offset', sa.Integer(), nullable=True))
    op.add_column('extracted_relationships', sa.Column('extraction_provider', sa.String(length=100), nullable=True))
    op.add_column('extracted_relationships', sa.Column('extraction_version', sa.String(length=50), nullable=True))
    op.add_column('extracted_relationships', sa.Column('reviewer_identity', sa.String(length=100), nullable=True))
    op.add_column('extracted_relationships', sa.Column('review_rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_relationships', 'review_rationale')
    op.drop_column('extracted_relationships', 'reviewer_identity')
    op.drop_column('extracted_relationships', 'extraction_version')
    op.drop_column('extracted_relationships', 'extraction_provider')
    op.drop_column('extracted_relationships', 'end_offset')
    op.drop_column('extracted_relationships', 'start_offset')
    op.drop_column('extracted_entities', 'review_rationale')
    op.drop_column('extracted_entities', 'reviewer_identity')
    op.drop_column('extracted_entities', 'extraction_version')
    op.drop_column('extracted_entities', 'extraction_provider')
    op.drop_column('extracted_entities', 'end_offset')
    op.drop_column('extracted_entities', 'start_offset')
    op.drop_column('extracted_entities', 'source_text')
    op.drop_column('extracted_entities', 'original_value')
    # ### end Alembic commands ###
