"""Add extraction model registry.

Revision ID: 9327cbe94283
Revises: 4bcc147a3094
Create Date: 2026-09-04 15:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9327cbe94283'
down_revision = '4bcc147a3094'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('extraction_version', sa.String(length=50), nullable=False),
    sa.Column('label_schema_version', sa.String(length=50), nullable=False),
    
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
    
    sa.Column('python_version', sa.String(length=50), nullable=True),
    sa.Column('spacy_version', sa.String(length=50), nullable=True),
    
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('train_document_ids', sa.JSON(), nullable=True),
    sa.Column('validation_document_ids', sa.JSON(), nullable=True),
    sa.Column('test_document_ids', sa.JSON(), nullable=True),
    
    sa.Column('label_distribution', sa.JSON(), nullable=True),
    sa.Column('training_metrics', sa.JSON(), nullable=True),
    sa.Column('test_metrics', sa.JSON(), nullable=True),
    
    sa.Column('status', sa.String(length=50), nullable=False),
    
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_models_model_id'), 'extraction_models', ['model_id'], unique=True)
    op.create_index(op.f('ix_extraction_models_provider'), 'extraction_models', ['provider'], unique=False)
    op.create_index(op.f('ix_extraction_models_status'), 'extraction_models', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_models_status'), table_name='extraction_models')
    op.drop_index(op.f('ix_extraction_models_provider'), table_name='extraction_models')
    op.drop_index(op.f('ix_extraction_models_model_id'), table_name='extraction_models')
    op.drop_table('extraction_models')
    # ### end Alembic commands ###
