"""Add ModelArtifact table

Revision ID: b0d56ca02c54
Revises: 26712e160037
Create Date: 2026-09-02 23:12:31.494176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d56ca02c54'
down_revision: Union[str, Sequence[str], None] = '26712e160037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_artifacts',
    sa.Column('artifact_id', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('feature_version', sa.String(length=100), nullable=False),
    sa.Column('artifact_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
    sa.Column('scikit_learn_version', sa.String(length=50), nullable=False),
    sa.Column('python_version', sa.String(length=50), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=True),
    sa.Column('training_case_ids', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_model_artifacts_artifact_id'), 'model_artifacts', ['artifact_id'], unique=True)
    op.create_index('ix_model_artifacts_status', 'model_artifacts', ['status'], unique=False)
    op.create_index('ix_model_artifacts_versions', 'model_artifacts', ['model_version', 'dataset_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_artifacts_versions', table_name='model_artifacts')
    op.drop_index('ix_model_artifacts_status', table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_artifact_id'), table_name='model_artifacts')
    op.drop_table('model_artifacts')
    # ### end Alembic commands ###
